services:
  postgres:
    image: postgres:12
    container_name: postgres
    # disable ssl mode
    environment:
      POSTGRES_USER: tony
      POSTGRES_PASSWORD: t870101
      POSTGRES_DB: diets
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
volumes:
  postgres: