# docker use ollama, command: docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
version: '3.7'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama